In [22]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np

In [24]:
print(np.__version__)

1.21.5


In [25]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/joser/OneDrive/Documentos/Anaconda/Anaconda\\Lib

In [30]:
a = np.random.random((2, 3,5))
a

array([[[0.08100131, 0.41893413, 0.21934608, 0.37065825, 0.13643287],
        [0.32163849, 0.81655331, 0.85539302, 0.63142734, 0.92607968],
        [0.28591644, 0.13224009, 0.04791362, 0.00276322, 0.01559837]],

       [[0.7198435 , 0.71015686, 0.83525938, 0.17414887, 0.35927023],
        [0.66487907, 0.67735284, 0.65538244, 0.38556711, 0.72945496],
        [0.63848389, 0.28824204, 0.95185968, 0.86699903, 0.86211394]]])

In [31]:
print(a)

[[[0.08100131 0.41893413 0.21934608 0.37065825 0.13643287]
  [0.32163849 0.81655331 0.85539302 0.63142734 0.92607968]
  [0.28591644 0.13224009 0.04791362 0.00276322 0.01559837]]

 [[0.7198435  0.71015686 0.83525938 0.17414887 0.35927023]
  [0.66487907 0.67735284 0.65538244 0.38556711 0.72945496]
  [0.63848389 0.28824204 0.95185968 0.86699903 0.86211394]]]


In [33]:
b = np.ones((5,2,3))
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [34]:
a.size

30

In [35]:
b.size

30

In [40]:
c= np.reshape(b,[2, 3, 5])
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [45]:
d=np.add(a, c)
print(d)

[[[1.08100131 1.41893413 1.21934608 1.37065825 1.13643287]
  [1.32163849 1.81655331 1.85539302 1.63142734 1.92607968]
  [1.28591644 1.13224009 1.04791362 1.00276322 1.01559837]]

 [[1.7198435  1.71015686 1.83525938 1.17414887 1.35927023]
  [1.66487907 1.67735284 1.65538244 1.38556711 1.72945496]
  [1.63848389 1.28824204 1.95185968 1.86699903 1.86211394]]]


In [46]:
print(d)

[[[1.08100131 1.41893413 1.21934608 1.37065825 1.13643287]
  [1.32163849 1.81655331 1.85539302 1.63142734 1.92607968]
  [1.28591644 1.13224009 1.04791362 1.00276322 1.01559837]]

 [[1.7198435  1.71015686 1.83525938 1.17414887 1.35927023]
  [1.66487907 1.67735284 1.65538244 1.38556711 1.72945496]
  [1.63848389 1.28824204 1.95185968 1.86699903 1.86211394]]]


In [47]:
print(a)

[[[0.08100131 0.41893413 0.21934608 0.37065825 0.13643287]
  [0.32163849 0.81655331 0.85539302 0.63142734 0.92607968]
  [0.28591644 0.13224009 0.04791362 0.00276322 0.01559837]]

 [[0.7198435  0.71015686 0.83525938 0.17414887 0.35927023]
  [0.66487907 0.67735284 0.65538244 0.38556711 0.72945496]
  [0.63848389 0.28824204 0.95185968 0.86699903 0.86211394]]]


In [49]:
e = np.multiply(a, c)
print(e)

[[[0.08100131 0.41893413 0.21934608 0.37065825 0.13643287]
  [0.32163849 0.81655331 0.85539302 0.63142734 0.92607968]
  [0.28591644 0.13224009 0.04791362 0.00276322 0.01559837]]

 [[0.7198435  0.71015686 0.83525938 0.17414887 0.35927023]
  [0.66487907 0.67735284 0.65538244 0.38556711 0.72945496]
  [0.63848389 0.28824204 0.95185968 0.86699903 0.86211394]]]


In [71]:
d_max=d.max()
print(d_max)



1.9518596824277754


In [70]:
d_min=d.min()
print(d_min)



1.0027632162636761


In [69]:
d_mean=d.mean()
print(d_mean)

1.4926970012278198


In [83]:
f = np.empty((2, 3, 5), int)
print (f)

[[[  116960253  1072778184  1170857878  1073132532   163227696]
  [ 1072923249  1460549847  1073081911   997260156  1072836308]
  [ 1727758242  1073030510   887239862  1073549466 -1741482426]]

 [[ 1073590192 -1915314071  1073355347  -318204096  1073664312]
  [  481484102  1072993053  -941260840  1072831911   306461766]
  [ 1072743489  1899478924  1072696145   329814240  1072709604]]]


In [84]:
print(d)

[[[1.08100131 1.41893413 1.21934608 1.37065825 1.13643287]
  [1.32163849 1.81655331 1.85539302 1.63142734 1.92607968]
  [1.28591644 1.13224009 1.04791362 1.00276322 1.01559837]]

 [[1.7198435  1.71015686 1.83525938 1.17414887 1.35927023]
  [1.66487907 1.67735284 1.65538244 1.38556711 1.72945496]
  [1.63848389 1.28824204 1.95185968 1.86699903 1.86211394]]]


In [104]:
for i in range(2):
    for j in range(3):
        for x in range(5):
           
            if d[i][j][x] > d_min and x < d_mean:
                f[i][j][x]=25
            if d[i][j][x] > d_mean and x < d_max:
                f[i][j][x]=75
            if d[i][j][x]==d_mean:
                f[i][j][x]=50
            if d[i][j][x] == d.min():
                f[i][j][x]=0
            if d[i][j][x] == d.max():
                f[i][j][x]=100
                
            
print(f)
    
            


[[[ 25  25 100 100 100]
  [ 25  75 100 100 100]
  [ 25  25 100   0 100]]

 [[ 75  75 100 100 100]
  [ 75  75 100 100 100]
  [ 75  25 100 100 100]]]


In [80]:
lst=[0, 1, 2]

In [81]:
lst.replace[1, 3, 4]

AttributeError: 'list' object has no attribute 'replace'